
### GEOMETRY
/Geometry/Lab/starting_point 0
/Geometry/Lab/file_name "/data4/NEXT/users/paolafer/dev_area/nexus/petalx_new/vertices_LXe_128_128_50.root"
/Geometry/Pet2boxes/z_size 5. cm
/Geometry/Pet2boxes/max_step_size 1.0 mm
/Geometry/PetPlainDice/reflectivity 0.97
/Geometry/PetalX/SiPMpet_vis true


### GENERATOR
/Generator/DoubleParticle/particle e-
/Generator/DoubleParticle/min_energy 511 keV
/Generator/DoubleParticle/max_energy 511 keV
/Generator/DoubleParticle/region ANYTHING


#/Generator/Na22Generator/region CENTER
#/Generator/Na22Generator/min_costheta 0.981513
#/Generator/Na22Generator/max_costheta 1
#/Generator/Na22Generator/min_phi 0
#/Generator/Na22Generator/max_phi 6.28319
#/Generator/Na22Generator/solid_angle specific
#/Generator/Na22Generator/solid_angle_dis 4Pi



### PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/offScintillation false
/PhysicsList/Nexus/offCherenkov false


### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### OUTPUT FILE
/nexus/persistency/outputFile prova.next
