### ------------------------------------------------------------------
###  Basic configuration macro of the nexus physics that results 
###  in the definition of the ionization electron with no attached 
###  physics processes.
###
###  $Id: DefaultPhysicsList.mac 9183 2013-08-29 10:14:43Z jmalbos $
### ------------------------------------------------------------------

/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false