### --------------------------------------------------------
###
### --------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/Geometry/RegisterGeometry BLACK_BOX_NEW_26_5
#/Generator/RegisterGenerator SINGLE_PARTICLE
/Generator/RegisterGenerator SINGLE_PARTICLE_ANG
/PhysicsList/RegisterPhysics G4OpticalPhysics

### ACTIONS
/Actions/RegisterRunAction DEFAULT
/Actions/RegisterEventAction SAVE_ALL
/Actions/RegisterTrackingAction OPTICAL
/Actions/RegisterSteppingAction ANALYSIS

/nexus/RegisterMacro /data5/users/miryam/nexus/macros/configs/black_box_new_26_5.config.mac
