

### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/Geometry/RegisterGeometry NEXT_NEW

/Generator/RegisterGenerator ION_GUN

/Actions/RegisterTrackingAction VALIDATION
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterSteppingAction DEFAULT
/Actions/RegisterRunAction DEFAULT

/nexus/RegisterMacro macros/validation/NEW_valid_K40.config.mac
#/nexus/RegisterDelayedMacro macros/physics/Bi214.mac
