## ----------------------------------------------------------------------------
## nexus | NEW_valid_K40.init.mac
##
## Initialization macro to simulate K-40 decays to test gamma
## production in different versions of GEANT4.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------


### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/nexus/RegisterGeometry NextNew

/nexus/RegisterGenerator IonGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterTrackingAction ValidationTrackingAction
/nexus/RegisterEventAction DefaultEventAction

/nexus/RegisterMacro macros/validation/NEW_valid_K40.config.mac
#/nexus/RegisterMacro macros/validation/NEW_valid_Co60.config.mac
#/nexus/RegisterMacro macros/validation/NEW_valid_Bi214.config.mac
#/nexus/RegisterMacro macros/validation/NEW_valid_Tl208.config.mac

#/nexus/RegisterDelayedMacro macros/physics/Bi214.mac
