## ----------------------------------------------------------------------------
## nexus | NEW_valid_Bi214.config.mac
##
## Configuration macro to simulate Bi-214 decays to test gamma
## production in different versions of GEANT4.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

#VERBOSITY
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# GEOMETRY
/Geometry/NextNew/pressure 15. bar
/Geometry/NextNew/elfield false

# GENERATION
/Generator/IonGenerator/atomic_number 83
/Generator/IonGenerator/mass_number 214
/Generator/IonGenerator/region DICE_BOARD

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

# ACTIONS
/Actions/ValidationTrackingAction/valid_file NEW_valid.Bi214.DICE_BOARD.csv

# PERSISTENCY
/nexus/persistency/eventType background
/nexus/persistency/outputFile NEW_valid.Bi214.DICE_BOARD.next
