
#VERBOSITY
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# GEOMETRY
/Geometry/NextNew/pressure 15. bar
/Geometry/NextNew/elfield false
/Geometry/PmtR11410/SD_depth 4

# GENERATION
/Generator/IonGun/atomic_number 81
/Generator/IonGun/mass_number 208
/Generator/IonGun/region DICE_BOARD

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

# PERSISTENCY
/nexus/persistency/eventType background
/nexus/persistency/outputFile NEW_valid.Tl208.DICE_BOARD.next
