
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/control/execute macros/geometries/NextNew.mac


/Generator/IonGun/atomic_number 19
/Generator/IonGun/mass_number 40
/Generator/IonGun/region DICE_BOARD

# ACTIONS
#/Actions/DefaultEventAction/energy_threshold 0.6 MeV

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

/nexus/persistency/eventType background
/nexus/persistency/hdf5 true
/nexus/persistency/outputFile NEW_valid.K40.DICE_BOARD.next
