
#VERBOSITY
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# GEOMETRY
/Geometry/NextNew/pressure 15. bar
/Geometry/NextNew/elfield false
/Geometry/PmtR11410/SD_depth 4

# GENERATION
/Generator/IonGenerator/atomic_number 19
/Generator/IonGenerator/mass_number 40
/Generator/IonGenerator/region DICE_BOARD

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

# PERSISTENCY
/nexus/persistency/eventType background
/nexus/persistency/outputFile NEW_valid.K40.DICE_BOARD.next
