### --------------------------------------------------------
###  Config macro for the geometry Next New.
###  $Id: NextNew.mac $
### --------------------------------------------------------

/Geometry/Next100/shielding_vis false
/Geometry/NextNew/table_vis false
/Geometry/NextNew/ics_vis false
/Geometry/NextNew/vessel_vis true
/Geometry/NextNew/energy_plane_vis true
/Geometry/NextNew/enclosure_vis true
/Geometry/NextNew/tracking_plane_vis true
/Geometry/NextNew/kdb_vis false
/Geometry/NextNew/SiPMSensl_vis false
/Geometry/NextNew/PmtR11410_vis true
/Geometry/NextNew/field_cage_vis false


/Geometry/NextNew/pressure 15. bar
/Geometry/NextNew/sc_yield 16670.  1/MeV
/Geometry/NextNew/elfield false
