### --------------------------------------------------------
###  Example config macro for the geometry Next1 EL.
### --------------------------------------------------------

/Geometry/Next1EL/external_scintillator false
/Geometry/Next1EL/elfield false
/Geometry/Next1EL/tpb_coating true
/Geometry/Next1EL/pressure 10. bar
/Geometry/Next1EL/tracking_plane SIPM
/Geometry/Next1EL/sideport_posz -64. mm
/Geometry/Next1EL/elgrid_transparency .88
/Geometry/Next1EL/gate_transparency .76
/Geometry/Next1EL/sideport_angle 30. deg
#/Geometry/Next1EL/specific_vertex_X 10. mm 
#/Geometry/Next1EL/specific_vertex_Y 10. mm 
#/Geometry/Next1EL/specific_vertex_Z 10. mm 


