### --------------------------------------------------------
###  Config macro for the geometry Next New.
###  $Id: NextNew.mac $
### --------------------------------------------------------

/Geometry/Next100/shielding_vis true
/Geometry/NextNew/energy_plane_vis true
/Geometry/NextNew/enclosure_vis true

/Geometry/NextNew/tracking_plane_vis true
/Geometry/NextNew/SiPM11_vis true

/Geometry/NextNew/vessel_vis true

/Geometry/NextNew/pressure 15. bar
/Geometry/NextNew/sc_yield 16670.  1/MeV
/Geometry/NextNew/elfield false
