### --------------------------------------------------------
###  Example config macro for the double beta generator.
###  $Id: GenbbInterface.mac 8754 2013-06-19 15:15:13Z jmunoz $
### --------------------------------------------------------


# Decay0 Interface for bb0nu/bb2nu decays - (BB0nu: DecayMode 1), (BB2nu: DecayMode 4)
# use electron momenta extracted with the DECAY0 software
#/Generator/Decay0Interface/inputFile /home/lebrun/NEXT/recoRel3/Releases/NEXT_HEAD/sources/nexus/data/Xe136_bb0nu.genbb

# use C++ translation of DECAY0
/Generator/Decay0Interface/inputFile none
# for 0 neutrino  bb to Barium Ground state.
#/Generator/Decay0Interface/Xe136DecayMode 1
# for 2 neutrino  bb to Barium Ground state.
/Generator/Decay0Interface/Xe136DecayMode 4
/Generator/Decay0Interface/EnergyThreshold 0.5
#
/Generator/Decay0Interface/Ba136FinalState 0

/Generator/Decay0Interface/region ACTIVE
