## ----------------------------------------------------------------------------
## nexus | Ion.mac
##
## Example configuration macro of the IonGenerator for Tl-208 radioactive
## decays.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/Generator/IonGenerator/atomic_number 81
/Generator/IonGenerator/mass_number 208
/Generator/IonGenerator/region CENTER
