## ----------------------------------------------------------------------------
## nexus | iongen_kr83m.mac
##
## Example configuration macro of the IonGenerator for radioactive decays
## of Kr-83m in the active volume of the detector.
## ----------------------------------------------------------------------------

/Generator/IonGenerator/atomic_number 36
/Generator/IonGenerator/mass_number   83
/Generator/IonGenerator/energy_level  41.5569 keV
/Generator/IonGenerator/region        ACTIVE
