## ----------------------------------------------------------------------------
## nexus | pmtQE.mac
##
## Ancillary macro to define the parameters of optical photons to be used
## in the set-up geometry to extract PMT quantum efficiencies.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 4.95936772037 eV
/Generator/SingleParticle/max_energy 4.95936772037 eV
/Generator/SingleParticle/region POINT
/Generator/SingleParticle/momentum_X 0.
/Generator/SingleParticle/momentum_Y 0.
/Generator/SingleParticle/momentum_Z -1.