### --------------------------------------------------------
###  Example config macro for the single-particle generator.
###  $Id: SingleParticle.mac 9053 2013-08-05 10:13:56Z jmalbos $
### --------------------------------------------------------

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 4.95936772037 eV
/Generator/SingleParticle/max_energy 4.95936772037 eV
/Generator/SingleParticle/region POINT
/Generator/SingleParticle/momentum_X 0.
/Generator/SingleParticle/momentum_Y 0.
/Generator/SingleParticle/momentum_Z -1.