### -----------------------------------------------------------
### 
### -----------------------------------------------------------

#/control/execute macros/geometries/BlackBox.mac

/control/execute macros/generators/SingleParticle.mac

#/control/execute macros/physics/IonizationElectron.mac

#/Generator/SingleParticle/particle e-
/Generator/SingleParticle/particle opticalphoton
#/Generator/SingleParticle/particle geantino
#/Generator/SingleParticle/min_energy 1.5 MeV
#/Generator/SingleParticle/max_energy 2.5 MeV
#/Generator/SingleParticle/min_energy 7.2 eV
#/Generator/SingleParticle/max_energy 7.2 eV
/Generator/SingleParticle/min_energy 4. eV
/Generator/SingleParticle/max_energy 4. eV
/Generator/SingleParticle/region AD_HOC
#/Generator/SingleParticle/momentum_X 0.
#/Generator/SingleParticle/momentum_Y 0.
#/Generator/SingleParticle/momentum_Y 
#/Generator/SingleParticle/momentum_Z 
#/Generator/SingleParticle/momentum_Z 1.

/Geometry/BlackBox/specific_vertex_X 0. mm
/Geometry/BlackBox/specific_vertex_Y 0. mm
/Geometry/BlackBox/specific_vertex_Z 0. mm

/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#/tracking/verbose 1

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile testing_blackbox.next
