### -----------------------------------------------------------
### This init macro simulates the response of a SensL SiPM DICE
### board in the black box.
### -----------------------------------------------------------

/Generator/SingleParticle/particle opticalphoton
#/Generator/SingleParticle/particle geantino
/Generator/SingleParticle/min_energy 2.9 eV
/Generator/SingleParticle/max_energy 2.9 eV
/Generator/SingleParticle/region AD_HOC
#/Generator/SingleParticle/momentum_X 0.
#/Generator/SingleParticle/momentum_Y 0.
#/Generator/SingleParticle/momentum_Z -1.
/Generator/SingleParticle/min_costheta -1.
/Generator/SingleParticle/max_costheta -0.9935

/Geometry/BlackBoxDEMO/specific_vertex_X 0. mm
/Geometry/BlackBoxDEMO/specific_vertex_Y 0. mm
/Geometry/BlackBoxDEMO/specific_vertex_Z 0. mm
/Geometry/BlackBoxDEMO/dice_board_z_pos -50. cm
/Geometry/BlackBoxDEMO/rotation 75 deg
/Geometry/BlackBoxDEMO/mask_thickn 0. mm
/Geometry/BlackBoxDEMO/membrane_thickn 0. mm
/Geometry/BlackBoxDEMO/coating_thickn 0. mm
/Geometry/BlackBoxDEMO/hole_diameter 3.5 mm

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile bb_75deg_noepoxy.next
