## ----------------------------------------------------------------------------
## nexus | DEMOPP_plate.config.mac
##
## Configuration macro to simulate electrons in the DEMO++ geometry
## with a quartz plate as anode.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

# VERBOSITY
/run/verbose 1
/event/verbose 0
/tracking/verbose 0


# GEOMETRY
/Geometry/NextDemo/max_step_size 1. mm
/Geometry/NextDemo/pressure 8. bar
/Geometry/NextDemo/plate false
/Geometry/NextDemo/tracking_plane_type type1

######################################################

# GENERATION
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 1 MeV
/Generator/SingleParticle/max_energy 1 MeV
/Generator/SingleParticle/region  ACTIVE


# PHYSICS
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


# PERSISTENCY
/nexus/persistency/outputFile DEMO_electron

/nexus/random_seed 14562

