## ----------------------------------------------------------------------------
## nexus | DEMO_muons.config.mac
##
## Configuration macro to simulate muons in the NEXT-DEMO detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

# GEOMETRY
/Geometry/Next1EL/elfield false
/Geometry/Next1EL/tpb_coating true
/Geometry/Next1EL/external_scintillator false
/Geometry/Next1EL/sc_yield 19711 1/MeV
/Geometry/Next1EL/pressure 10. bar
/Geometry/Next1EL/tracking_plane SIPM
/Geometry/Next1EL/sideport_posz 60. mm
/Geometry/Next1EL/elgrid_transparency .88
/Geometry/Next1EL/gate_transparency .76
/Geometry/Next1EL/sideport_angle 30. deg
/Geometry/Next1EL/muonsGenerator true

# GENERATOR
/Generator/MuonGenerator/min_energy  4. GeV
/Generator/MuonGenerator/max_energy  4. GeV
/Generator/MuonGenerator/region MUONS

# ACTIONS
## /Actions/MuonsEventAction/min_energy 0.6 MeV
/Actions/MuonsEventAction/stringHist MuonsHist_1.root

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

# PERSISTENCY
/nexus/persistency/outputFile DEMO_muons.next
