## ----------------------------------------------------------------------------
## nexus | DEMO_muons.init.mac
##
## Initialization macro to simulate muons in the NEXT-DEMO detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/nexus/RegisterGeometry Next1EL

/nexus/RegisterGenerator MuonGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/Actions/RegisterTrackingAction DEFAULT
/Actions/RegisterEventAction MUONS
/Actions/RegisterRunAction DEFAULT

/nexus/RegisterMacro macros/DEMO_muons.config.mac

