### --------------------------------------------------------
###  Example to run the muons generator 
###  Author: Neus Lopez March <neus.lopez@ific.uv.es>    
###  date: 30 Jan 2014
###  Modification Ruth Weiss Babai
###  date: 29 Aug 2019
### --------------------------------------------------------

/run/verbose 1
/event/verbose 0
/tracking/verbose 0


# GEOMETRY
/control/execute macros/geometries/NextDemo.mac


/Geometry/NextDemo/sc_yield 19711 1/MeV

/Geometry/NextDemo/muonsGenerator true
/Geometry/NextDemo/max_step_size 1. mm

######################################################

# GENERATION
/Generator/MuonGenerator/min_energy  4. GeV
/Generator/MuonGenerator/max_energy  4. GeV
/Generator/MuonGenerator/region MUONS    

# ACTIONS
## /Actions/MuonsEventAction/energy_threshold 0.6 MeV
/Actions/MuonsEventAction/stringHist MuonsHist_1.root

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

# PERSISTENCY
#/nexus/persistency/hdf5 true                   # always BEFORE outputFile
/nexus/persistency/outputFile out_DEMO_muons.next
#/nexus/persistency/outputFile DEMO_muons.next

