## ----------------------------------------------------------------------------
## nexus | MagBox.config.mac
##
## Configuration macro to simulate single electrons in a magnetic detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

### VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

### GEOMETRY
/Geometry/MagBox/gas_name Xenon #(Xenon, Hydrogen, SeF6)
/Geometry/MagBox/pressure 20. bar
/Geometry/MagBox/mag_intensity 10.0 tesla
/Geometry/MagBox/max_step_size 1.0 mm

### GENERATOR
/Generator/SingleParticle/region CENTER
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 2447. keV
/Generator/SingleParticle/max_energy 2447. keV
#/Generator/SingleParticle/momentum_X  0 1 0

### PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

### PERSISTENCY
/nexus/persistency/outputFile output.next
