
### GEOMETRY (Xenon, Hydrogen, SeF6)
/Geometry/MagBox/gas_name Xenon
/Geometry/MagBox/pressure 20. bar
/Geometry/MagBox/mag_intensity 10.0 tesla
/Geometry/MagBox/max_step_size 1.0 mm


### GENERATOR
#/Generator/IonGun/atomic_number 83
#/Generator/IonGun/mass_number 214
#/Generator/IonGun/region ENCLOSURE_WINDOW

/Generator/SingleParticle/region CENTER
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 2447. keV
/Generator/SingleParticle/max_energy 2447. keV
#/Generator/SingleParticle/momentum_X  0.
#/Generator/SingleParticle/momentum_Y  1.
#/Generator/SingleParticle/momentum_Z  0.

#/Generator/Decay0Interface/inputFile /data4/NEXT/NEXTNEW/decay0/Xe136_bb0nu/Xe136_bb0nu_decay0.0.txt
#/Generator/Decay0Interface/region CENTER



### PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false


### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### JOB CONTROL
#/nexus/persistency/outputFile tst.next
/nexus/persistency/outputFile output.next
