### --------------------------------------------------------
###  Configuration macro for the NEW detector geometry
###  This macro simulates Bi-214 decays from the dice boards
###  Author: Miquel Nebot Guinot <minegui@ific.uv.es>
###  date: 09 Sept 2013
### --------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/Geometry/NextNew/pressure 10. bar
/Geometry/NextNew/elfield false

/control/execute macros/geometries/NEWDefaultVisibility.mac


/Generator/IonGenerator/atomic_number 83
/Generator/IonGenerator/mass_number 214
/Generator/IonGenerator/region DICE_BOARD

# ACTIONS
/Actions/DefaultEventAction/energy_threshold 0.6 MeV

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

/nexus/persistency/eventType background
/nexus/persistency/outputFile NextNew.Bi214.DICE_BOARD.next
