### -----------------------------------------------------------------
###  This macro simulates the S1 optical response of the NEW detector
### -----------------------------------------------------------------

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# GENERATION
/Generator/ScintGenerator/region ACTIVE
/Generator/ScintGenerator/nphotons 1000

# GEOMETRY
/Geometry/NextNewOpticalGeometry/pressure 10. bar
/Geometry/PmtR11410/SD_depth 4
/Geometry/KDB/teflon_masks true

# PHYSICS
/control/execute macros/physics/IonizationElectron.mac
/nexus/persistency/outputFile S1_param.next

/nexus/random_seed -2
