## ----------------------------------------------------------------------------
## nexus | NEW_translated_bb0nu.init.mac
##
## Initialization macro to simulate bb0nu decays in the NEW detector geometry.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/nexus/RegisterGeometry NextNew

/nexus/RegisterGenerator Decay0Interface

/nexus/RegisterPersistencyManager PersistencyManager

/Actions/RegisterTrackingAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterRunAction DEFAULT

/nexus/RegisterMacro macros/NEW_translated_bb0nu.config.mac







