### --------------------------------------------------------
###  Configuration macro for the NEW detector geometry
###  This macro simulates an e+e- pair whose total kinetic energy
###  is 1592 keV, in the active volume
### --------------------------------------------------------

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Geometry
/Geometry/NextNew/elfield 0
/Geometry/NextNew/max_step_size 1. mm
/Geometry/NextNewOpticalGeometry/pressure 7. bar
/Geometry/NextNew/field_cage_vis true
/Geometry/PmtR11410/SD_depth 4

### Generation
/Generator/ElecPositronPair/min_energy 1.592 MeV
/Generator/ElecPositronPair/max_energy 1.592 MeV
/Generator/ElecPositronPair/region ACTIVE

/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/outputFile myoutput.next
