### ---------------------------------------------------------
### This init macro simulates geantinos in the NEW geometry
### shot from an specific vertex isotropically
### ---------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

# GENERATION
/Generator/SingleParticle/particle geantino
/Generator/SingleParticle/min_energy 1  eV
/Generator/SingleParticle/max_energy 1 keV
/Generator/SingleParticle/region AD_HOC
/Geometry/NextNew/specific_vertex  0 0 100 mm

# ACTIONS
#/Actions/SaveAllSteppingAction/select_particle geantino
#/Actions/SaveAllSteppingAction/select_volume   ACTIVE   #    full match
#/Actions/SaveAllSteppingAction/select_volume   TPB      # partial match
#/Actions/SaveAllSteppingAction/kill_after_selection true

# GEOMETRY
/Geometry/NextNew/pressure 10. bar

/nexus/persistency/save_strings false
/nexus/persistency/output_file geantinos.next
