### --------------------------------------------------------
###  This init macro simulates bb0nu decays
###  in the NEW detector geometry
### --------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/nexus/RegisterGeometry NextNew

/nexus/RegisterGenerator ECECGenerator

/nexus/RegisterTrackingAction DefaultTrackingAction
/nexus/RegisterEventAction DefaultEventAction
/nexus/RegisterRunAction DefaultRunAction

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterMacro macros/NEW_2nuECEC.config.mac
