## ----------------------------------------------------------------------------
## nexus | NEW_pair.init.mac
##
## Initialization macro to simulate an e+e- pair in the NEW detector geometry.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/Geometry/RegisterGeometry NEXT_NEW

/Generator/RegisterGenerator E+E-PAIR

/Actions/RegisterTrackingAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterRunAction DEFAULT

/nexus/RegisterMacro macros/NEW_pair.config.mac
