## ----------------------------------------------------------------------------
## nexus | NEW_hallA.config.mac
##
## Configuration macro to simulate neutrons from inside the HallA walls
## with NEW as the detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/Geometry/NextNew/pressure 10. bar
/Geometry/NextNew/elfield false
/Geometry/NextNew/lab_walls true

/control/execute macros/geometries/NEWDefaultVisibility.mac

/Generator/SingleParticle/particle neutron
/Generator/SingleParticle/min_energy 2 MeV
/Generator/SingleParticle/max_energy 2 MeV
/Generator/SingleParticle/region HALLA_INNER

/Actions/DefaultEventAction/min_energy 0.6 MeV

/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

/nexus/persistency/eventType background
/nexus/persistency/outputFile NextNew.HALLA_INNER.next
