## ----------------------------------------------------------------------------
## nexus | NEXT100.singleNeutron_2MeV.init.mac
##
## Initialization macro to simulate neutrons from a specific vertex
## in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4EmExtraPhysics
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics
#/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/physics_lists/em/MuonNuclear true

### GEOMETRY
/Geometry/RegisterGeometry NEXT100

### GENERATOR
/nexus/RegisterGenerator SingleParticleGenerator

### ACTIONS
/Actions/RegisterRunAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterTrackingAction DEFAULT

### CONFIGURATION
/nexus/RegisterDelayedMacro macros/physics/Xe137.mac
/nexus/RegisterMacro macros/NEXT100.singleNeutron_2MeV.config.mac
