## ----------------------------------------------------------------------------
## nexus | NEXT100.Neutron.init.mac
##
## Initialization macro to simulate neutrons from all around the lead shielding
## in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics
/PhysicsList/RegisterPhysics G4EmExtraPhysics
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics

/physics_lists/em/MuonNuclear true

### GEOMETRY
/nexus/RegisterGeometry Next100

### GENERATOR
/nexus/RegisterGenerator SingleParticleGenerator

### PERSISTENCY MANAGER
/nexus/RegisterPersistencyManager PersistencyManager

### ACTIONS
/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterEventAction DefaultEventAction
/nexus/RegisterTrackingAction DefaultTrackingAction

### CONFIGURATION
/nexus/RegisterDelayedMacro macros/physics/Xe137.mac
/nexus/RegisterMacro macros/NEXT100.Neutron.config.mac
