### --------------------------------------------------------
###  Next100: Initialization macro of nexus.
###  $Id: Next100.Neutron.mac 8754 2016-11-09 15:15:13Z minegui $
### --------------------------------------------------------


### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/PhysicsList/RegisterPhysics G4EmExtraPhysics
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics

/physics_lists/em/MuonNuclear true

### GEOMETRY
/Geometry/RegisterGeometry NEXT100

### GENERATOR
/Generator/RegisterGenerator NEUTRON_GENERATOR

### ACTIONS
/Actions/RegisterRunAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterSteppingAction DEFAULT
/Actions/RegisterTrackingAction DEFAULT


### EXTRA CONFIGURATION
/nexus/RegisterDelayedMacro Xe137.mac
/nexus/historyFile NEXT100.Neutron.pers.mac
/nexus/RegisterMacro NEXT100.Neutron.config.mac
