### This macro simulates individual neutrons in the NEW detector geometry
### It simulates only the inner part of the detector

### GEOMETRY
/Geometry/RegisterGeometry NEXT100


### GENERATOR
/Generator/RegisterGenerator SINGLE_PARTICLE


### ACTIONS
/Actions/RegisterRunAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterTrackingAction DEFAULT


### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4EmExtraPhysics
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics
#/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics


/physics_lists/em/MuonNuclear true


### EXTRA CONFIGURATION
/nexus/RegisterDelayedMacro macros/physics/Xe137.mac
/nexus/RegisterMacro macros/NEXT100.singleNeutron_2MeV.config.mac
