### GEOMETRY

# GAS SETTING
/Geometry/NextFlex/gas              enrichedXe
/Geometry/NextFlex/gas_pressure     15. bar
/Geometry/NextFlex/gas_temperature  300. kelvin
/Geometry/NextFlex/e_lifetime       1000. ms

# ACTIVE
/Geometry/NextFlex/active_length      116. cm
/Geometry/NextFlex/drift_transv_diff  1. mm/sqrt(cm)
/Geometry/NextFlex/drift_long_diff    .3 mm/sqrt(cm)

# FIELD CAGE
/Geometry/NextFlex/buffer_length    280. mm

/Geometry/NextFlex/cathode_transparency .98
/Geometry/NextFlex/anode_transparency   .88
/Geometry/NextFlex/gate_transparency    .88

/Geometry/NextFlex/el_gap_length    10.  mm
/Geometry/NextFlex/el_field_on      true
/Geometry/NextFlex/el_field_int     16. kilovolt/cm
/Geometry/NextFlex/el_transv_diff   0. mm/sqrt(cm)
/Geometry/NextFlex/el_long_diff     0. mm/sqrt(cm)

/Geometry/NextFlex/fc_wls_mat       TPB

/Geometry/NextFlex/fc_with_fibers   true
/Geometry/NextFlex/fiber_mat        EJ280
/Geometry/NextFlex/fiber_claddings  2

/Geometry/NextFlex/fiber_sensor_pde           1.
/Geometry/NextFlex/fiber_sensor_time_binning  5. ns


# ENERGY PLANE
/Geometry/NextFlex/ep_with_PMTs         true
/Geometry/NextFlex/ep_with_teflon       true
/Geometry/NextFlex/ep_copper_thickness  12. cm
/Geometry/NextFlex/ep_wls_mat           TPB

/Geometry/PmtR11410/SD_depth            3
/Geometry/PmtR11410/time_binning        20. ns

# TRACKING PLANE
/Geometry/NextFlex/tp_copper_thickness  12. cm
/Geometry/NextFlex/tp_teflon_thickness   5. mm
/Geometry/NextFlex/tp_teflon_hole_diam   7. mm
/Geometry/NextFlex/tp_wls_mat           TPB
/Geometry/NextFlex/tp_sipm_anode_dist   10. mm
/Geometry/NextFlex/tp_sipm_sizeX        1.3 mm
/Geometry/NextFlex/tp_sipm_sizeY        1.3 mm
/Geometry/NextFlex/tp_sipm_pitchX       15. mm
/Geometry/NextFlex/tp_sipm_pitchY       15. mm
/Geometry/NextFlex/tp_sipm_time_binning 5.  ns

# ICS
/Geometry/NextFlex/ics_thickness  12. cm

# VERBOSITY
/Geometry/NextFlex/verbosity     true
/Geometry/NextFlex/fc_verbosity  true
/Geometry/NextFlex/ep_verbosity  true
/Geometry/NextFlex/tp_verbosity  true

# VISIBILITIES
/Geometry/NextFlex/fc_visibility  true
/Geometry/NextFlex/ep_visibility  true
/Geometry/PmtR11410/visibility    true
/Geometry/NextFlex/tp_visibility  true
/Geometry/NextFlex/ics_visibility true


### GENERATOR
# Scint generator
#/Generator/ScintGenerator/region AD_HOC
#/Geometry/NextFlex/specific_vertex_X 0. mm
#/Geometry/NextFlex/specific_vertex_Y 0. mm
#/Geometry/NextFlex/specific_vertex_Z 500. mm
## (Kripton: 1046, 1MeV: 25510, Qbb: 62704)
#/Generator/ScintGenerator/nphotons 100000

# Single Particle
#/Generator/SingleParticle/region      AD_HOC
#/Geometry/NextFlex/specific_vertex_X  0. mm
#/Geometry/NextFlex/specific_vertex_Y  535. mm
#/Geometry/NextFlex/specific_vertex_Z  100. mm
#/Generator/SingleParticle/particle   geantino
##/Generator/SingleParticle/particle   opticalphoton
##/Generator/SingleParticle/particle   e-
##/Generator/SingleParticle/particle   alpha
#/Generator/SingleParticle/min_energy 10.0 keV
#/Generator/SingleParticle/max_energy 10.0 keV
##/Generator/SingleParticle/min_energy 7.20625 eV
##/Generator/SingleParticle/max_energy 7.20625 eV
##/Generator/SingleParticle/min_energy 2.454 MeV
##/Generator/SingleParticle/max_energy 2.454 MeV
#/Generator/SingleParticle/momentum_X 0.
#/Generator/SingleParticle/momentum_Y 0.
#/Generator/SingleParticle/momentum_Z -1.

# Kripton
/Generator/Kr83mGenerator/region  ACTIVE


### ACTIONS
#/Actions/DefaultEventAction/energy_threshold 2.3 MeV


### PHYSICS
/process/optical/scintillation/setTrackSecondariesFirst true
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true


### VERBOSITY
/control/verbose   0
/run/verbose       0
/event/verbose     0
/tracking/verbose  0


### CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile tst.NextFlex.next
