## ----------------------------------------------------------------------------
## nexus | NEXT100_muons_lsc.config.mac
##
## Configuration macro to simulate muons according to the distribution
## measured at LSC, in the NEXT-100 geometry.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

### VERBOSITY
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0
/process/had/verbose 0

### JOB CONTROL
/nexus/random_seed 17392

### GEOMETRY
/Geometry/Next100/pressure 15 bar
/Geometry/Next100/gas enrichedXe
/Geometry/Next100/elfield false
/Geometry/Next100/lab_walls true

### GENERATOR
/Generator/MuonAngleGenerator/region HALLA_OUTER
/Generator/MuonAngleGenerator/min_energy 100 GeV
/Generator/MuonAngleGenerator/max_energy 2000 GeV
/Generator/MuonAngleGenerator/azimuth_rotation 150 deg

# Angle only: za, # Angle + Energy: zae
/Generator/MuonAngleGenerator/angle_dist za

# DataFile: data/MuonAnaAllRuns.csv, # SimulationFile: data/SimulatedMuonsProposalMCEq.csv
# SimulationFile (Angle + Energy): data/SimulatedMuonsProposalMCEqEnergy.csv
/Generator/MuonAngleGenerator/angle_file data/SimulatedMuonsProposalMCEq.csv

### ACTIONS
/Actions/DefaultEventAction/min_energy 0.01 MeV


### PHYSICS (for fast simulation)
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

### PERSISTENCY
/nexus/persistency/start_id 0
/nexus/persistency/outputFile Next100Muons_hallA_example.next
