### GEOMETRY
/Geometry/Next100/pressure 15. bar
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/elfield false
/Geometry/Next100/xenon_type enriched

/Geometry/Next100/shielding_vis false
/Geometry/Next100/vessel_vis false
/Geometry/Next100/ics_vis false
/Geometry/Next100/field_cage_vis false
/Geometry/Next100/grids_vis false
/Geometry/Next100/energy_plane_vis false
/Geometry/Next100/tracking_plane_vis false
/Geometry/PmtR11410/SD_depth 3


### GENERATOR
# Single Particle
/Generator/SingleParticle/particle neutron
/Generator/SingleParticle/min_energy 2. MeV
/Generator/SingleParticle/max_energy 2. MeV
/Generator/SingleParticle/region AD_HOC
/Geometry/Next100/specific_vertex_X 0. mm
/Geometry/Next100/specific_vertex_Y 2400. mm
/Geometry/Next100/specific_vertex_Z 0. mm
/Generator/SingleParticle/momentum_X 0.
/Generator/SingleParticle/momentum_Y -1.
/Generator/SingleParticle/momentum_Z 0.


### ACTIONS
#/Actions/ElSimEventAction/max_energy 3. MeV
#/Actions/DefaultEventAction/energy_threshold 0. MeV
#/Actions/DefaultEventAction/max_energy 3. MeV


### PHYSICS (For fast Simulation)
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


### VERBOSITIES
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### JOB CONTROL
#/nexus/random_seed 0
/nexus/persistency/eventType background
/nexus/persistency/outputFile NEXT100.singleNeutron_2MeV.next
