### GEOMETRY

# GAS SETTING
/Geometry/NextFlex/gas              enrichedXe
/Geometry/NextFlex/gas_pressure     15. bar
/Geometry/NextFlex/gas_temperature  300. kelvin

# ACTIVE
/Geometry/NextFlex/active_length      130. cm
/Geometry/NextFlex/drift_transv_diff  1. mm/sqrt(cm)
/Geometry/NextFlex/drift_long_diff    .3 mm/sqrt(cm)

# FIELD CAGE
/Geometry/NextFlex/buffer_length     282. mm
/Geometry/NextFlex/el_gap_length     10.  mm
/Geometry/NextFlex/el_field_on       true
/Geometry/NextFlex/el_field_int      34.5 kilovolt/cm
/Geometry/NextFlex/el_transv_diff    0. mm/sqrt(cm)
/Geometry/NextFlex/el_long_diff      0. mm/sqrt(cm)
/Geometry/NextFlex/fc_wls_mat        TPB
/Geometry/NextFlex/fc_with_fibers    true
/Geometry/NextFlex/fiber_mat         EJ280
/Geometry/NextFlex/fiber_claddings   2
/Geometry/NextFlex/fiber_sensor_pde  1.

# ENERGY PLANE
/Geometry/NextFlex/ep_with_PMTs         true
/Geometry/NextFlex/ep_with_teflon       true
/Geometry/NextFlex/ep_copper_thickness  12. cm
/Geometry/NextFlex/ep_wls_mat           TPB
/Geometry/PmtR11410/SD_depth            3

# ICS
#/Geometry/NextFlex/ics_thickness  12. cm

# VERBOSITY
/Geometry/NextFlex/verbosity    true
/Geometry/NextFlex/fc_verbosity true
/Geometry/NextFlex/ep_verbosity true

# VISIBILITIES
/Geometry/NextFlex/fc_visibility true
/Geometry/NextFlex/ep_visibility true
/Geometry/PmtR11410/visibility   true


### GENERATOR
# S1 generator
#/Generator/S1generator/region AD_HOC
#/Geometry/NextFlex/specific_vertex_X 0. mm
#/Geometry/NextFlex/specific_vertex_Y 0. mm
#/Geometry/NextFlex/specific_vertex_Z 0. mm
#/Generator/S1generator/nphotons 25510

# Single Particle
/Generator/SingleParticle/region AD_HOC
/Geometry/NextFlex/specific_vertex_X 125. mm
/Geometry/NextFlex/specific_vertex_Y 0. mm
/Geometry/NextFlex/specific_vertex_Z 100. mm
#/Generator/SingleParticle/particle geantino
#/Generator/SingleParticle/particle e-
#/Generator/SingleParticle/particle alpha
#/Generator/SingleParticle/min_energy 0.001 MeV
#/Generator/SingleParticle/max_energy 0.001 MeV
/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 7.20625 eV
/Generator/SingleParticle/max_energy 7.20625 eV
#/Generator/SingleParticle/min_energy 2.8 eV
#/Generator/SingleParticle/max_energy 2.8 eV
/Generator/SingleParticle/momentum_X 0.
/Generator/SingleParticle/momentum_Y 0.
/Generator/SingleParticle/momentum_Z 0.


### PHYSICS
#/process/optical/scintillation/setTrackSecondariesFirst true
/PhysicsList/Nexus/clustering false
/PhysicsList/Nexus/drift false
/PhysicsList/Nexus/electroluminescence false


### VERBOSITY
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### CONTROL
/nexus/random_seed -1
/nexus/persistency/hdf5 true
/nexus/persistency/start_id 0
/nexus/persistency/outputFile tst.NextFlex.next
