## ----------------------------------------------------------------------------
## nexus | NEXT100.singleNeutron_2MeV.config.mac
##
## Configuration macro to simulate neutrons from a specific vertex
## in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

### VERBOSITY
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0
/process/had/verbose 0

### JOB CONTROL
/nexus/random_seed 12345

### GEOMETRY
/Geometry/Next100/pressure 15. bar
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/elfield false
/Geometry/Next100/gas enrichedXe
/Geometry/Next100/specific_vertex 0. 2400. 0. mm

/control/execute macros/geometries/NEXT100DefaultVisibility.mac

### GENERATOR
# Single Particle
/Generator/SingleParticle/particle neutron
/Generator/SingleParticle/min_energy 2. MeV
/Generator/SingleParticle/max_energy 2. MeV
/Generator/SingleParticle/region AD_HOC
/Generator/SingleParticle/momentum 0 -1 0

### ACTIONS
#/Actions/DefaultEventAction/min_energy 0. MeV
#/Actions/DefaultEventAction/max_energy 3. MeV

### PHYSICS (for fast simulation)
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

### PERSISTENCY
/nexus/persistency/eventType background
/nexus/persistency/outputFile NEXT100.singleNeutron_2MeV.next
