### --------------------------------------------------------
###  Next100: Configuration macro
###  $Id: Next100.Neutron.config.mac 8758 2016-11-09 15:12:45Z minegui $
### --------------------------------------------------------


##### ACTIONS #####


##### JOB CONTROL #####
#/nexus/random_seed 0
/nexus/persistency/eventType background
/nexus/persistency/outputFile Next100.Neutron.next



##### GEOMETRY #####
/Geometry/Next100/pressure 15. bar
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/elfield false


/Geometry/Next100/shielding_vis false
/Geometry/Next100/vessel_vis false
/Geometry/Next100/ics_vis false
/Geometry/Next100/field_cage_vis false
/Geometry/Next100/grids_vis false
/Geometry/Next100/energy_plane_vis false
/Geometry/Next100/tracking_plane_vis false
/Geometry/PmtR11410/SD_depth 3



##### GENERATOR #####

# Region options: EXTERNAL, SHIELDING_LEAD, SHIELDING_STEEL, SHIELDING_GAS, SHIELDING_STRUCT
#                 VESSEL, VESSEL_FLANGES, VESSEL_TRACKING_ENDCAP, VESSEL_ENERGY_ENDCAP
#		  ICS, DB_PLUG,
#		  FIELD_CAGE, ACTIVE, CARRIER_PLATE, ENCLOSURE, ENCLOSURE_WINDOW, ENCLOSURE_PAD,
#		  PMT_BODY, PMT, TRK_SUPPORT, DICE_BOARD, EL_TABLE

# Single Particle
#/Generator/SingleParticle/particle e-
#/Generator/SingleParticle/min_energy 1.0 MeV
#/Generator/SingleParticle/max_energy 2.0 MeV
#/Generator/SingleParticle/region DICE_BOARD
#/Generator/SingleParticle/momentum_direction (0., 0., 1.)


# Deacy0 Interface for bb0nu/bb2nu decays
#/Generator/Decay0Interface/inputFile /data4/NEXT/NEXTNEW/decay0/Xe136_bb0nu/Xe136_bb0nu_decay0.0.txt
#/Generator/Decay0Interface/region ACTIVE

# Ion Gun for background decays
#/Generator/IonGun/atomic_number 83
#/Generator/IonGun/mass_number 214
#/Generator/IonGun/region FIELD_CAGE

#Neutron generator for cosmogenics
/Generator/NeutronGenerator/min_energy 100 MeV
/Generator/NeutronGenerator/max_energy 	100 MeV
/Generator/NeutronGenerator/region EXTERNAL

# ACTIONS
#/Actions/ElSimEventAction/max_energy 3. MeV
#/Actions/DefaultEventAction/energy_threshold 0. MeV
#/Actions/DefaultEventAction/max_energy 3. MeV

## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

##### VERBOSITIES #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


