### GEOMETRY
/Geometry/Next100/pressure 15 bar
/Geometry/Next100/gas enrichedXe
/Geometry/Next100/elfield false

### GENERATOR
/Generator/MuonAngleGenerator/region EXTERNAL
/Generator/MuonAngleGenerator/min_energy 200 GeV
/Generator/MuonAngleGenerator/max_energy 250 GeV
/Generator/MuonAngleGenerator/azimuth_rotation 150 deg
/Generator/MuonAngleGenerator/angle_file histos/MuonAnaAllRuns.root
/Generator/MuonAngleGenerator/angle_dist za

### ACTIONS
/Actions/DefaultEventAction/energy_threshold 0.01 MeV


### PHYSICS (For fast Simulation)
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


### VERBOSITIES
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### JOB CONTROL
/nexus/random_seed 17392
/nexus/persistency/start_id 0
/nexus/persistency/outputFile Next100Muons_lsc_example.next