### --------------------------------------------------------
###  Next100: Configuration macro
###  $Id: Next100.config.mac 8758 2013-06-15 11:12:45Z jmunoz $
### --------------------------------------------------------

##### VERBOSITIES #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0



##### GEOMETRY #####
/Geometry/Next100/pressure 15. bar
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/elfield 1
/Geometry/Next100/el_table_binning 1. mm
/Geometry/Next100/el_table_point_id 0


### Generation
/Generator/SingleParticle/particle ie-
/Generator/SingleParticle/min_energy 1. eV
/Generator/SingleParticle/max_energy 1. eV
/Generator/SingleParticle/region EL_TABLE


##### JOB CONTROL #####
/nexus/persistency/outputFile Next100_table.next

/nexus/random_seed -2 





