


#Use NEXT_NEW to simulate the hole geometry
#Use OPTICAL_GEOMETRY to simulate only the inner part of the detector


/control/execute macros/physics/DefaultPhysicsList.mac

/Geometry/RegisterGeometry NEXT_NEW

/Generator/RegisterGenerator SINGLE_PARTICLE   

/Actions/RegisterTrackingAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterSteppingAction DEFAULT
/Actions/RegisterRunAction DEFAULT

/nexus/RegisterMacro macros/nexus_NEW.Tl.cathode.config.mac









