### --------------------------------------------------------
###  Example 1: Configuration macro
###  $Id: nexus_example1.config.mac 9053 2013-08-05 10:13:56Z jmalbos $
### --------------------------------------------------------

/run/verbose 1
/event/verbose 0
/tracking/verbose 2
/control/execute macros/generators/IonGun.mac
/control/execute macros/geometries/XeSphere.mac
/nexus/persistency/outputFile nexus.root