

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# GENERATION
/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy  2614.0 keV
/Generator/SingleParticle/max_energy 2614.0 keV
/Generator/SingleParticle/region SOURCE_PORT_CATHODE

# GEOMETRY
/Geometry/NextNew/pressure 15. bar
/Geometry/NextNew/sc_yield 16670. 1/MeV
/Geometry/NextNew/elfield false
/Geometry/PmtR11410/SD_depth 4
/Geometry/KDB/teflon_masks true

# PHYSICS
/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/outputFile output.next
