## ----------------------------------------------------------------------------
## nexus | nexus_example3.config.mac
##
## Configuration macro to simulate individual particles
## in the NEXT-DEMO detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed -2

/control/execute macros/generators/SingleParticle.mac

/control/execute macros/geometries/Next1EL.mac

/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/outputFile nexus.next
