### ------------------------------------------------------------------
###  Example 1: Initialization macro of nexus.
###
###  $Id$
### ------------------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/Geometry/RegisterGeometry XE_SPHERE

/Generator/RegisterGenerator SINGLE_PARTICLE

/Actions/RegisterRunAction DEFAULT

/exus/RegisterMacro macros/params.macro

/nexus/RegisterMacro macros/params.macro







