## ----------------------------------------------------------------------------
## nexus | nexus_example1.init.mac
##
## Initialization macro to simulate individual particles
## in a sphere of xenon.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/nexus/RegisterGeometry XeSphere

/nexus/RegisterGenerator SingleParticleGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/Actions/RegisterRunAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterTrackingAction DEFAULT

/nexus/RegisterMacro macros/nexus_example1.config.mac
