### --------------------------------------------------------
###  NextNew: Configuration macro
###  $Id:$
### --------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# GENERATION
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 40. keV
/Generator/SingleParticle/max_energy 40. keV
/Generator/SingleParticle/region ACTIVE

# GEOMETRY
/Geometry/NextNew/pressure 15. bar
/Geometry/NextNew/sc_yield 16670. 1/MeV
/Geometry/NextNew/elfield false


# PHYSICS
/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/outputFile output.next
