## ----------------------------------------------------------------------------
## nexus | nexus_OpticalFibre.config.mac
##
## Configuration macro to simulate photons
## along an optical fibre.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/Geometry/OpticalFibre/length 10. cm
/Geometry/OpticalFibre/radius 1. mm
/Geometry/OpticalFibre/core_mat "EJ280"
/Geometry/OpticalFibre/num_fibers 9

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/region BODY_VOL
/Generator/SingleParticle/min_energy 2.88 eV
/Generator/SingleParticle/max_energy 2.88 eV
#/Generator/SingleParticle/min_costheta 1
#/Generator/SingleParticle/max_costheta 1
#/Generator/SingleParticle/min_phi 0
#/Generator/SingleParticle/max_phi 0

/process/optical/processActivation Cerenkov false

### PHYSICS
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

/nexus/persistency/outputFile OpticalFibre.next