### ------------------------------------------------------------------
###  Example 2: Configuration macro
###
###  $Id: nexus_example1.config.mac 9053 2013-08-05 10:13:56Z jmalbos $
### ------------------------------------------------------------------

#/control/execute macros/geometries/CylindricChamber.mac

/control/execute macros/generators/IonGun.mac

/run/verbose 1
/event/verbose 0
/tracking/verbose 2

/nexus/persistency/outputFile nexus.root