### ------------------------------------------------------------------
###  Example 2: Configuration macro
###
### ------------------------------------------------------------------

#/control/execute macros/geometries/CylindricChamber.mac

/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy  1. keV
/Generator/SingleParticle/max_energy 10. keV
/Generator/SingleParticle/region CENTER

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/nexus/persistency/outputFile data/nexus_example2.root
