### --------------------------------------------------------
###  Example 1: Initialization macro of nexus.
###  $Id$
### --------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/Geometry/RegisterGeometry XE_SPHERE

/Generator/RegisterGenerator SINGLE_PARTICLE   

/Actions/RegisterTrackingAction DEFAULT

/nexus/RegisterMacro macros/nexus_example1.config.mac







