### --------------------------------------------------------
###  Example 1: Initialization macro of nexus.
###  $Id: nexus_example1.init.mac 9053 2013-08-05 10:13:56Z jmalbos $
### --------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/Geometry/RegisterGeometry XE_SPHERE

/Generator/RegisterGenerator ION_GUN   

/Actions/RegisterTrackingAction DEFAULT

/nexus/RegisterMacro macros/nexus_example2.config.mac







