### --------------------------------------------------------
###  NextNew: Configuration macro
###  $Id$
### --------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# GENERATION
/Generator/Kr83mGenerator/region ACTIVE

# GEOMETRY
/Geometry/NextNew/pressure 15. bar
/Geometry/NextNew/elfield false
/Geometry/PmtR11410/SD_depth 4
/Geometry/KDB/teflon_masks true

# PHYSICS
/control/execute macros/physics/IonizationElectron.mac

/nexus/persistency/outputFile output.next
#/nexus/persistency/start_id 100
