
### GEOMETRY
/Geometry/Lab/starting_point 0
/Geometry/Lab/file_name "/data4/NEXT/users/paolafer/dev_area/nexus/petalx_new/vertices_LXe_128_128_50.root"
#/Geometry/Lab/det_type LXe
/Geometry/PetLXeCell/z_size 5. cm
/Geometry/PetLXeCell/max_step_size 1.0 mm
/Geometry/PetLXeCell/physics true
#/Geometry/PetLXeCell/SiPMtype plots

/Geometry/PetPlainDice/reflectivity 0.97
#/Geometry/PetKDBFixedPitch/reflectivity 0.97
#/Geometry/PetKDBFixedPitch/kdb_vis true
#/Geometry/SiPMpet/SiPMpet_vis true
#/Geometry/SiPMpet/physics false
#/Geometry/SiPMpet/refr_index 1.54
#/Geometry/SiPMpet/pde 0.2

### GENERATOR
/Generator/DoubleParticle/particle e-
/Generator/DoubleParticle/min_energy 511 keV
/Generator/DoubleParticle/max_energy 511 keV
/Generator/DoubleParticle/region ANYTHING


#/Generator/Na22Generator/region CENTER
#/Generator/Na22Generator/min_costheta 0.981513
#/Generator/Na22Generator/max_costheta 1
#/Generator/Na22Generator/min_phi 0
#/Generator/Na22Generator/max_phi 6.28319
#/Generator/Na22Generator/solid_angle specific
#/Generator/Na22Generator/solid_angle_dis 4Pi

### OUTPUT FILE
/nexus/persistency/outputFile prova.pet

### PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/offScintillation true
/PhysicsList/Nexus/offCherenkov false

##ACTIONS
/Actions/AnalysisTrackingAction/file_number 1
/Actions/AnalysisSteppingAction/file_number 1


### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 1



