
### GEOMETRY
/Geometry/PetalX2/z_size 5. cm
/Geometry/PetalX2/max_step_size 1.0 mm
/Geometry/PetalX/kdb_vis false
/Geometry/PetalX/plain_dice_vis true
/Geometry/PetalX/SiPMpet_vis false

/Geometry/PetalX/plain_columns 6
/Geometry/PetalX/plain_rows 6
/Geometry/PetalX/kdb_columns 6
/Geometry/PetalX/kdb_rows 6


### GENERATOR

/Generator/SingleParticle/region SURFACE
/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 511. keV
/Generator/SingleParticle/max_energy 511. keV
/Generator/SingleParticle/momentum_X 0.
/Generator/SingleParticle/momentum_Y 0.
/Generator/SingleParticle/momentum_Z 1.


### PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false


### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### OUTPUT FILE
/nexus/persistency/outputFile test.next
