
### GEOMETRY
/Geometry/PetalX/z_size 5. cm
/Geometry/PetalX/max_step_size 1.0 mm
/Geometry/PetalX/kdb_vis false
/Geometry/PetalX/plain_dice_vis true
/Geometry/PetalX/SiPMpet_vis false

/Geometry/PetalX/plain_columns 6
/Geometry/PetalX/plain_rows 6
/Geometry/PetalX/kdb_columns 6
/Geometry/PetalX/kdb_rows 6

### GENERATOR

/Generator/SingleParticle/region OUTSIDE
/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 511. keV
/Generator/SingleParticle/max_energy 511. keV
#/Generator/SingleParticle/momentum_X 0.
#/Generator/SingleParticle/momentum_Y 0.
#/Generator/SingleParticle/momentum_Z 1.
/Generator/SingleParticle/min_costheta 0.989949
/Generator/SingleParticle/max_costheta 1.
/Generator/SingleParticle/min_phi 0.
/Generator/SingleParticle/max_phi 6.28319


### PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/offCompt false


### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### OUTPUT FILE
/nexus/persistency/outputFile test.next
