
### GEOMETRY

/Geometry/FullRingInfinity/depth 3. cm
/Geometry/FullRingInfinity/pitch 7. mm
/Geometry/FullRingInfinity/inner_radius 165. mm
/Geometry/FullRingInfinity/sipm_rows 20
/Geometry/FullRingInfinity/instrumented_faces 1
/Geometry/FullRingInfinity/cryostat_width 18 cm
/Geometry/FullRingInfinity/specific_vertex_X 0. cm
/Geometry/FullRingInfinity/specific_vertex_Y 166. mm
/Geometry/FullRingInfinity/specific_vertex_Z 0. cm

/Geometry/SiPMpet/efficiency 0.2
/Geometry/SiPMpet/visibility true
/Geometry/SiPMpet/time_binning 1. microsecond
/Geometry/SiPMpet/size 6. mm


### GENERATION
/Generator/ScintGenerator/region AD_HOC
/Generator/ScintGenerator/nphotons 100000

### PHYSICS
/PhysicsList/Nexus/offScintillation false
/PhysicsList/Nexus/offCherenkov false


### VERBOSITIES
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/nexus/random_seed 132313

### OUTPUT FILE
/nexus/persistency/start_id 10
/nexus/persistency/outputFile full_ring_lut.pet
