
### GEOMETRY
/Geometry/Petit/lab_side 1. m
/Geometry/Petit/dist_between_cells 50. cm

/Geometry/PetitModule/max_step_size 1. mm
/Geometry/PetitModule/det_in_diam 8. cm
/Geometry/PetitModule/det_length 30. cm
/Geometry/PetitModule/two_instrumented_planes 1

#/Geometry/PetPlainDice/reflectivity 0.97
/Geometry/SiPMpet/time_binning 200 nanosecond


### GENERATOR
/Generator/Na22Generator/region CENTER

#/Generator/Na22Generator/region AD_HOC
#/Geometry/Petit/specific_vertex_X 0. mm
#/Geometry/Petit/specific_vertex_Y 0. mm
#/Geometry/Petit/specific_vertex_Z 0. mm


### VISIBILITIES
/Geometry/PetitPlainDice/visibility 0
/Geometry/SiPMpet/visibility 1
/Geometry/PetitModule/visibility_dices 1


### OUTPUT FILE
/nexus/persistency/outputFile prueba_petit_100.pet


### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0



