## ----------------------------------------------------------------------------
## nexus | pmtQE.mac
##
## Ancillary macro to define the parameters of optical photons to be used
## in the set-up geometry to extract PMT quantum efficiencies.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose      1
/event/verbose    1
/tracking/verbose 1

/Geometry/SIPM_QE_setup/z_dist 2.5 cm

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 2.0 eV
/Generator/SingleParticle/max_energy 2.5 eV
/Generator/SingleParticle/region POINT
/Generator/SingleParticle/momentum_X 0.
/Generator/SingleParticle/momentum_Y 0.
/Generator/SingleParticle/momentum_Z -1.

/nexus/random_seed 1
/nexus/persistency/outputFile SIPM_QE
