## ----------------------------------------------------------------------------
## nexus | test.init.mac
##
## Initialization macro to test vertices.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/nexus/RegisterGeometry Next100

/nexus/RegisterGenerator SingleParticleGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterTrackingAction DefaultTrackingAction
/nexus/RegisterEventAction SaveAllEventAction
/nexus/RegisterRunAction DefaultRunAction

/nexus/RegisterMacro macros/test.config.mac
