/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/Geometry/RegisterGeometry NEXT_NEW

/Generator/RegisterGenerator SINGLE_PARTICLE

/Actions/RegisterTrackingAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterSteppingAction DEFAULT
/Actions/RegisterStackingAction DEFAULT
/Actions/RegisterRunAction DEFAULT

/nexus/RegisterMacro pytest/test_macros/NEW_single_electron.config.mac
