##### JOB CONTROL #####
/nexus/persistency/outputFile pytest/Next100_sensdet


##### GEOMETRY #####
/Geometry/Next100/elfield true
/Geometry/Next100/EL_field 10 kV/cm
/Geometry/Next100/pressure 10. bar
/Geometry/Next100/sc_yield 10000 1/MeV
/Geometry/Next100/max_step_size 5. mm

/Geometry/PmtR11410/SD_depth 3

##### GENERATOR #####
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 50. keV
/Generator/SingleParticle/max_energy 50. keV
/Generator/SingleParticle/region CENTER

##### VERBOSITIES #####
/run/verbose 1
/event/verbose 0
/tracking/verbose 0